version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run :
          name : clone repo
          command : 'rm -rf NGL && git clone https://github.com:/NCCA/NGL'
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run :
           name : Install tools
           command: 'apt-get update && sudo apt-get install -y cmake libglfw3-dev qtbase5-dev libpython2.7-dev'

      - run :
          name : Install vcpkg
          command : 'export CMAKE_BUILD_PARALLEL_LEVEL=2 && git clone https://github.com/microsoft/vcpkg && cd vcpkg && ./bootstrap-vcpkg.sh && ./vcpkg install glfw3 openimageio  gtest  freetype glm  rapidjson rapidxm '
      
      - run : 
          name : Build NGL
          command : 'cd NGL && git checkout master && cd mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake && make -j2'
      - run :
          name : NGL c++ Tests
          command : 'cd //root/project/NGL/build && ./NGLTests -g'
