name: BuildNGL

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Run vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgArguments: 'glfw3  gtest fmt freetype glm  rapidjson rapidxml'
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      env:
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxxflags}}
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}}  \
               -DNO_OIIO=1 \
               $GITHUB_WORKSPACE
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: |
        threads=`nproc`
        cmake --build . --config ${{matrix.build_type}} --parallel $threads
    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: NGLTests -g
