name: BuildNGL

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: install vcpkg
      run : |
        git clone --depth 1  https://github.com/microsoft/vcpkg ~/vcpkg 
        cd ~/vcpkg 
        ./bootstrap-vcpkg.sh
        ./vcpkg install glfw3  gtest fmt freetype glm  rapidjson rapidxml 
    - name: Configure
      working-directory: ${{runner.workspace}}/build
      env:
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxxflags}}
      run: |
        mkdir build 
        cd build
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}}  \
               -DNO_OIIO=1 .. \
               
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: |
        threads=`nproc`
        cmake --build . --config ${{matrix.build_type}} --parallel $threads
    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: NGLTests -g
