name: BuildNGL

on: [push, pull_request]

jobs:
  build:
    runs-on:  windows-latest
    steps:
    - uses: actions/checkout@v2 
    
    - name: install vcpkg
      run : |
        git clone --depth 1  https://github.com/microsoft/vcpkg $HOME/vcpkg 
        cd $HOME/vcpkg 
        bootstrap-vcpkg.bat
        vcpkg install glfw3 gtest fmt freetype glm  rapidjson rapidxml  
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE="$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake" -DNO_OIIO=1  -DCMAKE_BUILD_TYPE=Debug  ..

               
    - name: Build
      run: |
        cd build
        
        cmake --build . 
    - name: Test
      run: |
        cd build
        ./NGLTests -g
